/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;

/**
 *
 * @author Lucas
 */
public class CadastrarConsultaUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarConsulta
     */
    public CadastrarConsultaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPPainelPrincipal = new javax.swing.JPanel();
        JPainelPaciente = new javax.swing.JPanel();
        JLNomePaciente = new javax.swing.JLabel();
        JTFNomePaciente = new javax.swing.JTextField();
        JBProcurarPaciente = new javax.swing.JButton();
        JLCodigoPaciente = new javax.swing.JLabel();
        JTFCodigoPaciente = new javax.swing.JTextField();
        JSPPaciente = new javax.swing.JScrollPane();
        JTabelaPaciente = new javax.swing.JTable();
        JLDataConsulta = new javax.swing.JLabel();
        JFTDataConsulta = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        JPainelPaciente8 = new javax.swing.JPanel();
        JLNomePaciente8 = new javax.swing.JLabel();
        JTFNomePaciente8 = new javax.swing.JTextField();
        JBProcurarPaciente8 = new javax.swing.JButton();
        JLCodigoPaciente8 = new javax.swing.JLabel();
        JTFCodigoPaciente8 = new javax.swing.JTextField();
        JSPPaciente8 = new javax.swing.JScrollPane();
        JTabelaPaciente8 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JBSalvar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();

        setClosable(true);

        JPPainelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        JPainelPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        JLNomePaciente.setText("Nome do Paciente :");

        JBProcurarPaciente.setText("Procurar");

        JLCodigoPaciente.setText("Codigo Paciente :");

        JTabelaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Nome do Paciente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTabelaPaciente.getTableHeader().setReorderingAllowed(false);
        JSPPaciente.setViewportView(JTabelaPaciente);
        JTabelaPaciente.getColumnModel().getColumn(0).setMinWidth(100);
        JTabelaPaciente.getColumnModel().getColumn(0).setMaxWidth(200);

        javax.swing.GroupLayout JPainelPacienteLayout = new javax.swing.GroupLayout(JPainelPaciente);
        JPainelPaciente.setLayout(JPainelPacienteLayout);
        JPainelPacienteLayout.setHorizontalGroup(
            JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPainelPacienteLayout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addComponent(JBProcurarPaciente)
                .addContainerGap())
            .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPainelPacienteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JSPPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                        .addGroup(JPainelPacienteLayout.createSequentialGroup()
                            .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JLNomePaciente)
                                .addComponent(JLCodigoPaciente))
                            .addGap(18, 18, 18)
                            .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JTFNomePaciente)
                                .addGroup(JPainelPacienteLayout.createSequentialGroup()
                                    .addComponent(JTFCodigoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 167, Short.MAX_VALUE)))))
                    .addContainerGap()))
        );
        JPainelPacienteLayout.setVerticalGroup(
            JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPainelPacienteLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(JBProcurarPaciente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPainelPacienteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLNomePaciente)
                        .addComponent(JTFNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLCodigoPaciente)
                        .addComponent(JTFCodigoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(JSPPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        JLDataConsulta.setText("Data da Consulta :");

        try {
            JFTDataConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setText("Procedimento:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        JPainelPaciente8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Médico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        JLNomePaciente8.setText("Nome do Médico:");

        JBProcurarPaciente8.setText("Procurar");

        JLCodigoPaciente8.setText("CRM:");

        JTFCodigoPaciente8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCodigoPaciente8ActionPerformed(evt);
            }
        });

        JTabelaPaciente8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Nome do Paciente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JSPPaciente8.setViewportView(JTabelaPaciente8);
        JTabelaPaciente8.getColumnModel().getColumn(0).setMinWidth(100);
        JTabelaPaciente8.getColumnModel().getColumn(0).setMaxWidth(200);

        javax.swing.GroupLayout JPainelPaciente8Layout = new javax.swing.GroupLayout(JPainelPaciente8);
        JPainelPaciente8.setLayout(JPainelPaciente8Layout);
        JPainelPaciente8Layout.setHorizontalGroup(
            JPainelPaciente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPainelPaciente8Layout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addComponent(JBProcurarPaciente8)
                .addContainerGap())
            .addGroup(JPainelPaciente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPainelPaciente8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(JPainelPaciente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JSPPaciente8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(JPainelPaciente8Layout.createSequentialGroup()
                            .addGroup(JPainelPaciente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JLNomePaciente8)
                                .addComponent(JLCodigoPaciente8))
                            .addGap(18, 18, 18)
                            .addGroup(JPainelPaciente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JTFNomePaciente8, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                .addGroup(JPainelPaciente8Layout.createSequentialGroup()
                                    .addComponent(JTFCodigoPaciente8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 178, Short.MAX_VALUE)))))
                    .addContainerGap()))
        );
        JPainelPaciente8Layout.setVerticalGroup(
            JPainelPaciente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPainelPaciente8Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(JBProcurarPaciente8)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(JPainelPaciente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPainelPaciente8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(JPainelPaciente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLNomePaciente8)
                        .addComponent(JTFNomePaciente8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(JPainelPaciente8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLCodigoPaciente8)
                        .addComponent(JTFCodigoPaciente8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(JSPPaciente8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Observações:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout JPPainelPrincipalLayout = new javax.swing.GroupLayout(JPPainelPrincipal);
        JPPainelPrincipal.setLayout(JPPainelPrincipalLayout);
        JPPainelPrincipalLayout.setHorizontalGroup(
            JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(JPPainelPrincipalLayout.createSequentialGroup()
                        .addGroup(JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPPainelPrincipalLayout.createSequentialGroup()
                                .addGroup(JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JPainelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JPPainelPrincipalLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(JLDataConsulta)
                                        .addGap(18, 18, 18)
                                        .addComponent(JFTDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(JPPainelPrincipalLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(JPPainelPrincipalLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(JPainelPaciente8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JPPainelPrincipalLayout.setVerticalGroup(
            JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPPainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLDataConsulta)
                    .addComponent(JFTDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPainelPaciente8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPainelPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        JBSalvar.setText("Salvar");
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });

        JBCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(JBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPPainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPPainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBSalvar)
                    .addComponent(JBCancelar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBSalvarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void JTFCodigoPaciente8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCodigoPaciente8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFCodigoPaciente8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBProcurarPaciente;
    private javax.swing.JButton JBProcurarPaciente1;
    private javax.swing.JButton JBProcurarPaciente2;
    private javax.swing.JButton JBProcurarPaciente3;
    private javax.swing.JButton JBProcurarPaciente4;
    private javax.swing.JButton JBProcurarPaciente5;
    private javax.swing.JButton JBProcurarPaciente6;
    private javax.swing.JButton JBProcurarPaciente7;
    private javax.swing.JButton JBProcurarPaciente8;
    private javax.swing.JButton JBSalvar;
    private javax.swing.JFormattedTextField JFTDataConsulta;
    private javax.swing.JLabel JLCodigoPaciente;
    private javax.swing.JLabel JLCodigoPaciente1;
    private javax.swing.JLabel JLCodigoPaciente2;
    private javax.swing.JLabel JLCodigoPaciente3;
    private javax.swing.JLabel JLCodigoPaciente4;
    private javax.swing.JLabel JLCodigoPaciente5;
    private javax.swing.JLabel JLCodigoPaciente6;
    private javax.swing.JLabel JLCodigoPaciente7;
    private javax.swing.JLabel JLCodigoPaciente8;
    private javax.swing.JLabel JLDataConsulta;
    private javax.swing.JLabel JLNomePaciente;
    private javax.swing.JLabel JLNomePaciente1;
    private javax.swing.JLabel JLNomePaciente2;
    private javax.swing.JLabel JLNomePaciente3;
    private javax.swing.JLabel JLNomePaciente4;
    private javax.swing.JLabel JLNomePaciente5;
    private javax.swing.JLabel JLNomePaciente6;
    private javax.swing.JLabel JLNomePaciente7;
    private javax.swing.JLabel JLNomePaciente8;
    private javax.swing.JPanel JPPainelPrincipal;
    private javax.swing.JPanel JPainelPaciente;
    private javax.swing.JPanel JPainelPaciente1;
    private javax.swing.JPanel JPainelPaciente2;
    private javax.swing.JPanel JPainelPaciente3;
    private javax.swing.JPanel JPainelPaciente4;
    private javax.swing.JPanel JPainelPaciente5;
    private javax.swing.JPanel JPainelPaciente6;
    private javax.swing.JPanel JPainelPaciente7;
    private javax.swing.JPanel JPainelPaciente8;
    private javax.swing.JScrollPane JSPPaciente;
    private javax.swing.JScrollPane JSPPaciente1;
    private javax.swing.JScrollPane JSPPaciente2;
    private javax.swing.JScrollPane JSPPaciente3;
    private javax.swing.JScrollPane JSPPaciente4;
    private javax.swing.JScrollPane JSPPaciente5;
    private javax.swing.JScrollPane JSPPaciente6;
    private javax.swing.JScrollPane JSPPaciente7;
    private javax.swing.JScrollPane JSPPaciente8;
    private javax.swing.JTextField JTFCodigoPaciente;
    private javax.swing.JTextField JTFCodigoPaciente1;
    private javax.swing.JTextField JTFCodigoPaciente2;
    private javax.swing.JTextField JTFCodigoPaciente3;
    private javax.swing.JTextField JTFCodigoPaciente4;
    private javax.swing.JTextField JTFCodigoPaciente5;
    private javax.swing.JTextField JTFCodigoPaciente6;
    private javax.swing.JTextField JTFCodigoPaciente7;
    private javax.swing.JTextField JTFCodigoPaciente8;
    private javax.swing.JTextField JTFNomePaciente;
    private javax.swing.JTextField JTFNomePaciente1;
    private javax.swing.JTextField JTFNomePaciente2;
    private javax.swing.JTextField JTFNomePaciente3;
    private javax.swing.JTextField JTFNomePaciente4;
    private javax.swing.JTextField JTFNomePaciente5;
    private javax.swing.JTextField JTFNomePaciente6;
    private javax.swing.JTextField JTFNomePaciente7;
    private javax.swing.JTextField JTFNomePaciente8;
    private javax.swing.JTable JTabelaPaciente;
    private javax.swing.JTable JTabelaPaciente1;
    private javax.swing.JTable JTabelaPaciente2;
    private javax.swing.JTable JTabelaPaciente3;
    private javax.swing.JTable JTabelaPaciente4;
    private javax.swing.JTable JTabelaPaciente5;
    private javax.swing.JTable JTabelaPaciente6;
    private javax.swing.JTable JTabelaPaciente7;
    private javax.swing.JTable JTabelaPaciente8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
