/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ConsultaController;
import controller.MedicoController;
import controller.PacienteController;
import controller.ProcedimentoController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Consulta;
import model.Medico;
import model.Paciente;
import model.Procedimento;

/**
 *
 * @author Lucas
 */
public class CadastrarConsultaUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarConsulta
     */
    private List<Paciente> listaPaciente;
    private List<Medico> listaMedico;
    private List<Procedimento> listaProcedimento;
    private DefaultTableModel modelo, modeloMedico;
    private Consulta consultaAnt;
    
    public CadastrarConsultaUI(Consulta consulta) {
        initComponents();
        comboBoxProcedimento();
        
        this.zerarModeloMedico();
        try {
            this.listaMedico = MedicoController.obterInstancia().listarMedico();
        } catch (Exception ex) {
            Logger.getLogger(CadastrarConsultaUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.zerarModeloPaciente();
        try {
            this.listaPaciente = PacienteController.obterInstancia().listarPaciente();
        } catch (Exception ex) {
            Logger.getLogger(CadastrarConsultaUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(consulta != null){
            consultaAnt = consulta;
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            JFTDataConsulta.setText(sdf.format(consulta.getData()));
            //JTAProcedimento.setText(consulta.getProcedimento()); Virou ComboBOX
            JTAObservacao.setText(consulta.getObservacao());
            
            for (Medico listaMedico1 : this.listaMedico) {
                if (consulta.getCodMedico().equals(listaMedico1.getCodigo())) {
                    modeloMedico.addRow(new Object[]{listaMedico1.getCrm(), listaMedico1.getNome()});
                }
            }

            for (Paciente listaPaciente1 : this.listaPaciente) {
                if (consulta.getCodPaciente().equals(listaPaciente1.getCodigo())) {
                    modelo.addRow(new Object[]{listaPaciente1.getCodigo(), listaPaciente1.getNome()});
                }
            }
           
            JTabelaMedico.setModel(modeloMedico);
            JTabelaPaciente.setModel(modelo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPPainelPrincipal = new javax.swing.JPanel();
        JPainelPaciente = new javax.swing.JPanel();
        JLNomePaciente = new javax.swing.JLabel();
        JTFNomePaciente = new javax.swing.JTextField();
        JBProcurarPaciente = new javax.swing.JButton();
        JLCodigoPaciente = new javax.swing.JLabel();
        JTFCodigoPaciente = new javax.swing.JTextField();
        JSPPaciente = new javax.swing.JScrollPane();
        JTabelaPaciente = new javax.swing.JTable();
        JLDataConsulta = new javax.swing.JLabel();
        JFTDataConsulta = new javax.swing.JFormattedTextField();
        JLProcedimento = new javax.swing.JLabel();
        JCBProcedimento = new javax.swing.JComboBox();
        JPainelMedico = new javax.swing.JPanel();
        JLNomeMedico = new javax.swing.JLabel();
        JTFNomeMedico = new javax.swing.JTextField();
        JBProcurarMedico = new javax.swing.JButton();
        JLCRMedico = new javax.swing.JLabel();
        JTFCRM = new javax.swing.JTextField();
        JSPMedico = new javax.swing.JScrollPane();
        JTabelaMedico = new javax.swing.JTable();
        JLMedico = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAObservacao = new javax.swing.JTextArea();
        JBSalvar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();

        setClosable(true);

        JPPainelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        JPainelPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        JLNomePaciente.setText("Nome do Paciente :");

        JBProcurarPaciente.setText("Procurar");
        JBProcurarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBProcurarPacienteActionPerformed(evt);
            }
        });

        JLCodigoPaciente.setText("Codigo Paciente :");

        JTabelaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Nome do Paciente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTabelaPaciente.getTableHeader().setReorderingAllowed(false);
        JSPPaciente.setViewportView(JTabelaPaciente);
        if (JTabelaPaciente.getColumnModel().getColumnCount() > 0) {
            JTabelaPaciente.getColumnModel().getColumn(0).setMinWidth(100);
            JTabelaPaciente.getColumnModel().getColumn(0).setMaxWidth(200);
        }

        javax.swing.GroupLayout JPainelPacienteLayout = new javax.swing.GroupLayout(JPainelPaciente);
        JPainelPaciente.setLayout(JPainelPacienteLayout);
        JPainelPacienteLayout.setHorizontalGroup(
            JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPainelPacienteLayout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(JBProcurarPaciente)
                .addContainerGap())
            .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPainelPacienteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JSPPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                        .addGroup(JPainelPacienteLayout.createSequentialGroup()
                            .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JLNomePaciente)
                                .addComponent(JLCodigoPaciente))
                            .addGap(18, 18, 18)
                            .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JTFNomePaciente)
                                .addGroup(JPainelPacienteLayout.createSequentialGroup()
                                    .addComponent(JTFCodigoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 167, Short.MAX_VALUE)))))
                    .addContainerGap()))
        );
        JPainelPacienteLayout.setVerticalGroup(
            JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPainelPacienteLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(JBProcurarPaciente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPainelPacienteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLNomePaciente)
                        .addComponent(JTFNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(JPainelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLCodigoPaciente)
                        .addComponent(JTFCodigoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(JSPPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        JLDataConsulta.setText("Data da Consulta :");

        try {
            JFTDataConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        JLProcedimento.setText("Procedimento:");

        JPainelMedico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Médico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        JLNomeMedico.setText("Nome do Médico:");

        JBProcurarMedico.setText("Procurar");
        JBProcurarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBProcurarMedicoActionPerformed(evt);
            }
        });

        JLCRMedico.setText("CRM:");

        JTabelaMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Nome do Paciente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JSPMedico.setViewportView(JTabelaMedico);
        if (JTabelaMedico.getColumnModel().getColumnCount() > 0) {
            JTabelaMedico.getColumnModel().getColumn(0).setMinWidth(100);
            JTabelaMedico.getColumnModel().getColumn(0).setMaxWidth(200);
        }

        javax.swing.GroupLayout JPainelMedicoLayout = new javax.swing.GroupLayout(JPainelMedico);
        JPainelMedico.setLayout(JPainelMedicoLayout);
        JPainelMedicoLayout.setHorizontalGroup(
            JPainelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPainelMedicoLayout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(JBProcurarMedico)
                .addContainerGap())
            .addGroup(JPainelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPainelMedicoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(JPainelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JSPMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(JPainelMedicoLayout.createSequentialGroup()
                            .addGroup(JPainelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JLNomeMedico)
                                .addComponent(JLCRMedico))
                            .addGap(18, 18, 18)
                            .addGroup(JPainelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JTFNomeMedico, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                .addGroup(JPainelMedicoLayout.createSequentialGroup()
                                    .addComponent(JTFCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 178, Short.MAX_VALUE)))))
                    .addContainerGap()))
        );
        JPainelMedicoLayout.setVerticalGroup(
            JPainelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPainelMedicoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(JBProcurarMedico)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(JPainelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPainelMedicoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(JPainelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLNomeMedico)
                        .addComponent(JTFNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(JPainelMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLCRMedico)
                        .addComponent(JTFCRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(JSPMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        JLMedico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JLMedico.setText("Observações:");

        JTAObservacao.setColumns(20);
        JTAObservacao.setRows(5);
        jScrollPane1.setViewportView(JTAObservacao);

        javax.swing.GroupLayout JPPainelPrincipalLayout = new javax.swing.GroupLayout(JPPainelPrincipal);
        JPPainelPrincipal.setLayout(JPPainelPrincipalLayout);
        JPPainelPrincipalLayout.setHorizontalGroup(
            JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(JPPainelPrincipalLayout.createSequentialGroup()
                        .addGroup(JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPPainelPrincipalLayout.createSequentialGroup()
                                .addGroup(JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JPainelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JPPainelPrincipalLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(JLDataConsulta)
                                        .addGap(18, 18, 18)
                                        .addComponent(JFTDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(JPPainelPrincipalLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(JLProcedimento)
                                        .addGap(18, 18, 18)
                                        .addComponent(JCBProcedimento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(JPPainelPrincipalLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(JPainelMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(JLMedico))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JPPainelPrincipalLayout.setVerticalGroup(
            JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPPainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLDataConsulta)
                    .addComponent(JFTDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLProcedimento)
                    .addComponent(JCBProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPainelMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPainelPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        JBSalvar.setText("Salvar");
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });

        JBCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(JBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPPainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPPainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBSalvar)
                    .addComponent(JBCancelar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBProcurarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBProcurarPacienteActionPerformed
       this.zerarModeloPaciente();
       try{
       JTabelaPaciente.setModel(verificarPaciente(modelo));
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage(),"ERRO",0);
       }
    }//GEN-LAST:event_JBProcurarPacienteActionPerformed

    private void JBProcurarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBProcurarMedicoActionPerformed
       this.zerarModeloMedico();
       try{
       JTabelaMedico.setModel(verificarMedico(modeloMedico));
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage(),"ERRO",0);
       }
    }//GEN-LAST:event_JBProcurarMedicoActionPerformed

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        try{
            if(consultaAnt != null){
                int linhaMedico = JTabelaMedico.getSelectedRow();
                int linhaPaciente = JTabelaPaciente.getSelectedRow();
                try{
                    consultaAnt.setCodMedico( this.verificaMedico((int) modeloMedico.getValueAt(linhaMedico,0)));
                    consultaAnt.setCodPaciente((int) modelo.getValueAt(linhaPaciente,0));
                    consultaAnt.setCodProcedimento(JCBProcedimento.getSelectedIndex());
                }catch(Exception e){
                    Logger.getLogger(CadastrarConsultaUI.class.getName()).log(Level.SEVERE, e.getMessage());
                }
                
                try{
                    // Manipulação da Data 
                    
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    Date data = sdf.parse(JFTDataConsulta.getText());
                    consultaAnt.setData(data);
                }catch(ParseException e){}
                
                // consultaAnt.setProcedimento(JTAProcedimento.getText()); Virou ComboBox
                consultaAnt.setObservacao(JTAObservacao.getText());
                
                ConsultaController.obterInstancia().alterar(consultaAnt);
                
            }else{
                Consulta consulta = new Consulta();
                // Obtenção das Linhas
                int linhaMedico = JTabelaMedico.getSelectedRow();
                int linhaPaciente = JTabelaPaciente.getSelectedRow();

               // Obtem os dados pela linha selecionada
                try{
                    consulta.setCodMedico(this.verificaMedico((int) modeloMedico.getValueAt(linhaMedico,0)));
                    consulta.setCodPaciente((int) modelo.getValueAt(linhaPaciente,0));
                    consulta.setCodProcedimento(JCBProcedimento.getSelectedIndex());
                }catch(Exception e){
                    Logger.getLogger(CadastrarConsultaUI.class.getName()).log(Level.SEVERE, e.getMessage());
                }
                
               // consulta.setProcedimento(JTAProcedimento.getText()); Virou ComboBox
                consulta.setObservacao(JTAObservacao.getText());

                try{
                    // Manipulação da Data 
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    Date data = sdf.parse(JFTDataConsulta.getText());
                    consulta.setData(data);
                }catch(ParseException e){}

                    ConsultaController.obterInstancia().cadastrar(consulta);
            }           
            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso !");
            this.dispose();            
        }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage(),"ERRO",0);
        }
    }//GEN-LAST:event_JBSalvarActionPerformed
            
    private DefaultTableModel verificarPaciente(DefaultTableModel modelo) throws Exception{
       String nome = JTFNomePaciente.getText();
       Integer codigo;
       try{
           codigo = Integer.parseInt(JTFCodigoPaciente.getText());
       }catch(NumberFormatException e){
           codigo = 0;
       }

       for(int i=0;i< this.listaPaciente.size(); i++){
          if(!nome.isEmpty() && codigo != 0){
              if(Objects.equals(this.listaPaciente.get(i).getCodigo(), codigo) && 
                       !this.listaPaciente.get(i).getNome().equals(nome)){
                  throw new Exception("Codigo e nome diferentes !!");
              }
       
              if(this.listaPaciente.get(i).getCodigo().equals(codigo)){
                  modelo.addRow(new Object[] {this.listaPaciente.get(i).getCodigo(),
                                              this.listaPaciente.get(i).getNome()});
              }              
          }else
          if(!nome.isEmpty() && codigo == 0){
              if(this.listaPaciente.get(i).getNome().contains(nome)){
                  modelo.addRow(new Object[] {this.listaPaciente.get(i).getCodigo(),
                                              this.listaPaciente.get(i).getNome()});
              }
          }else
          if(nome.isEmpty() && codigo != 0){
              if(this.listaPaciente.get(i).getCodigo().equals(codigo)){
                  modelo.addRow(new Object[] {this.listaPaciente.get(i).getCodigo(),
                                              this.listaPaciente.get(i).getNome()}); 
              }
          }else
          if(nome.isEmpty() && codigo ==0){
               modelo.addRow(new Object[] {this.listaPaciente.get(i).getCodigo(),
                                              this.listaPaciente.get(i).getNome()}); 
          }
       }
       
        if(modelo.getRowCount() != 0){
            return modelo;
        }else{
            throw new Exception("Nenhum dado Cadastrado com esses dados");
        }
    }
       
    private DefaultTableModel verificarMedico(DefaultTableModel modelo) throws Exception{
       String nome = JTFNomeMedico.getText();
       Integer codigo;
       try{
           codigo = Integer.parseInt(JTFCRM.getText());
       }catch(NumberFormatException e){
           codigo = 0;
       }
    
        for (Medico listaMedico1 : this.listaMedico) {
            if (!nome.isEmpty() && codigo != 0) {
                if (Objects.equals(listaMedico1.getCrm(), codigo) && !listaMedico1.getNome().equals(nome)) {
                    throw new Exception("Codigo e nome diferentes !!");
                }
                if (Objects.equals(listaMedico1.getCrm(), codigo)) {
                    modelo.addRow(new Object[]{listaMedico1.getCrm(), listaMedico1.getNome()});
                }
            } else if (!nome.isEmpty() && codigo == 0) {
                if (listaMedico1.getNome().contains(nome)) {
                    modelo.addRow(new Object[]{listaMedico1.getCrm(), listaMedico1.getNome()});
                }
            } else if (nome.isEmpty() && codigo != 0) {
                if (Objects.equals(listaMedico1.getCrm(), codigo)) {
                    modelo.addRow(new Object[]{listaMedico1.getCrm(), listaMedico1.getNome()});
                }
            } else if (nome.isEmpty() && codigo ==0) {
                modelo.addRow(new Object[]{listaMedico1.getCrm(), listaMedico1.getNome()});
            }
        }
              
        if(modelo.getRowCount() != 0){
            return modelo;
        }else{
            throw new Exception("Nenhum dado Cadastrado com esses dados");
        }
    }
    
     private void comboBoxProcedimento(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        try {
            this.listaProcedimento = ProcedimentoController.obterInstancia().obterLista();
        } catch (Exception ex) {
            Logger.getLogger(CadastrarMedicoUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Procedimento procedimento : this.listaProcedimento) {
            modelo.addElement(procedimento.getDescricao());
        }
        JCBProcedimento.setModel(modelo);
    }
       
    private void zerarModeloPaciente(){
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[] {"Codigo","Nome"});
    }
    
    private void zerarModeloMedico(){
        modeloMedico = new DefaultTableModel();
        modeloMedico.setColumnIdentifiers(new String[] {"CRM","Nome"});
    }
    
    private Integer verificaMedico(Integer crm){
        for(int i=0; i < this.listaMedico.size();i++){
            if(this.listaMedico.get(i).getCrm().equals(crm)){
                return this.listaMedico.get(i).getCodigo();
            }
        }
        return null;
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBProcurarMedico;
    private javax.swing.JButton JBProcurarPaciente;
    private javax.swing.JButton JBSalvar;
    private javax.swing.JComboBox JCBProcedimento;
    private javax.swing.JFormattedTextField JFTDataConsulta;
    private javax.swing.JLabel JLCRMedico;
    private javax.swing.JLabel JLCodigoPaciente;
    private javax.swing.JLabel JLDataConsulta;
    private javax.swing.JLabel JLMedico;
    private javax.swing.JLabel JLNomeMedico;
    private javax.swing.JLabel JLNomePaciente;
    private javax.swing.JLabel JLProcedimento;
    private javax.swing.JPanel JPPainelPrincipal;
    private javax.swing.JPanel JPainelMedico;
    private javax.swing.JPanel JPainelPaciente;
    private javax.swing.JScrollPane JSPMedico;
    private javax.swing.JScrollPane JSPPaciente;
    private javax.swing.JTextArea JTAObservacao;
    private javax.swing.JTextField JTFCRM;
    private javax.swing.JTextField JTFCodigoPaciente;
    private javax.swing.JTextField JTFNomeMedico;
    private javax.swing.JTextField JTFNomePaciente;
    private javax.swing.JTable JTabelaMedico;
    private javax.swing.JTable JTabelaPaciente;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
